### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [ya0201/qwer-ps1#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by ya0201** [comment]
Hi @unixorn , thanks for comment!
I added a license file 😄  -- https://github.com/ya0201/qwer-ps1/pull/3
